[colors.bright]
black = "#988ba2"
blue = "#96cdfb"
cyan = "#89dceb"
green = "#abe9b3"
magenta = "#f5c2e7"
red = "#f28fad"
white = "#d9e0ee"
yellow = "#fae3b0"

[colors.normal]
black = "#6e6c7e"
blue = "#96cdfb"
cyan = "#89dceb"
green = "#abe9b3"
magenta = "#f5c2e7"
red = "#f28fad"
white = "#d9e0ee"
yellow = "#fae3b0"

[colors.primary]
background = "#2E3440"
foreground = "#f8f8f2"
