#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/launcher.rasi"

# Run
if [[ ! `pidof rofi` ]]; then
    rofi \
        -show drun \
        -theme ${RASI}
else
	pkill rofi
fi
